### PR TITLE
feat(design-system): delete design system

### PR DESCRIPTION
**Pull request by samuel-gomez-axa**
Transfered the Design System to an another repository (design-system)
So deleting all files and tasks that concern the design system
The new design system is available here : https://axaguildev.github.io/design-system/

### CODE REVIEW

**Review by arnaudforaison — DISMISSED** [review]
Good job @samuel-gomez-axa

**Review by xballoy — DISMISSED** [review]
Good job 👍

**Comment by gcruchon** [comment]
Why deleting it? :-(

It's quite convinient to have them sync'ed in the same repo.

Actually, I even added a requirement to update the design system as part of the components' docs.

**Comment by xballoy** [comment]
You have some prettier issues in your build. I think it's related to #718 (new Prettier rules)

**Comment by xballoy** [comment]
I fixed the CI errors in #730

**Comment by xballoy** [comment]
You can rebase with master, it should fix your CI errors

**Comment by samuel-gomez-axa** [comment]
@gcruchon it's in the roadmap to exit the Design System to another repository.
@arnaudforaison has launched a discussion about it and we decided this with main contributors.

**Review by arnaudforaison — APPROVED** [review]

**Review by xballoy — APPROVED** [review]

**Pull request merged**
