### PR TITLE
feat: add props to footer component to hide icon

### PR DESCRIPTION
**Pull request by barry-thierno**
## Related issue
#77 
### Reference to the issue

`Here you can add link to related issue`
Logo link in the footer #77
### Description of the issue

`Your description`

### Person(s) for reviewing proposed changes

`You can add @mention here`

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

### CODE REVIEW

**Comment by barry-thierno** [comment]
@johnmeunier here is a proposition for enhancement  you create about footer component.
Thank for you validation.

**Comment by samuel-gomez-axa** [comment]
Hello @barry-thierno , thanks for your contribution :)

In issue 77, Johnathan wanted to make optional logo link by a new  property.
You had a new property to do this: **isIconHidden**

I would prefer to use the **icon** accessories to show / hide the logo and use the **href** accessories to show / hide the logo link. I think is more flexible

What do you think ?

**Comment by barry-thierno** [comment]
I'm agree with your proposition

**Comment by youf-olivier** [comment]
Any Update for this PR ?

**Comment by guillaumechervetaxa** [comment]
Hi @barry-thierno, any Update for this PR ?

**Pull request merged**
