### PR TITLE
fix(NumberInput): isValidNumber for support zero value in the component numberInput

### PR DESCRIPTION
**Pull request by Gparquet**
### Reference to the issue

`Here you can add link to related issue`

### Description of the issue

`Your description`

### Person(s) for reviewing proposed changes

`You can add @mention here`

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

### CODE REVIEW

**Comment by Gparquet** [comment]
@youf-olivier it's ok, i fix this problem

**Comment by youf-olivier** [comment]
> @youf-olivier it's ok, i fix this problem

Great !! Thanks for your PR :)

**Comment by guillaume-chervet** [comment]
@youf-olivier tu as mis un truc qui bloque le merge ^^

**Comment by youf-olivier** [comment]
Oui comme ça je peux valider le change

**Pull request merged**
