### PR TITLE
Update react-dropzone dependency

### LINKED ISSUE #796: Upgrade react-dropzone
In package `@axa-fr/react-toolkit-form-input-file` we are using [react-dropzone 4.2.11](https://github.com/react-dropzone/react-dropzone/releases/tag/v4.2.11) which is very old (more than 2 years old).
We should upgrade it to the [latest version ](https://github.com/react-dropzone/react-dropzone/releases).

There's no migration guide, we must check every release on Github to see if there's a breaking change that affect us. However as it seems to follow semver we can probably just check the major versions.

### PR DESCRIPTION
**Pull request by LunarzFR**
Fixes #796 

**Description**
I've updated the react-dropzone dependency for the FileInput component.
The update had an impact on the component so I did a little refacto.

**Question**
I have a question about the _...otherProps_, are they really necessary ? And if so, what are they used for in the case of this component?

### CODE REVIEW

**Comment by arnaudforaison** [comment]
Good job. I think otherProps is necessary but I'll be review when this component will be migrated to TS.
Why do you think isn't necessary ?

**Comment by LunarzFR** [comment]
> Good job. I think otherProps is necessary but I'll be review when this component will be migrated to TS.
> Why do you think isn't necessary ?

Because I don't see what kind of others props can be passed for an input file ?
I think everything is already there to use correctly this component.

**Comment by arnaudforaison** [comment]
Others props can be all html input attributes as aria, id, ...
Depends on dev needed

**Review by johnmeunier — APPROVED** [review]

**Review by arnaudforaison — COMMENTED** [review]
Le onChange ne sort pas les erreurs au même format. J'ai comparé le storybook actuel avec celui de ton code.
Je trouve ça mieux et maintenant on a l'erreur par contre le niveau d'imbrication est élevé

**Comment by LunarzFR** [comment]
> Le onChange ne sort pas les erreurs au même format. Mais c'est mieux maintenant.
> Vu avec @LunarzFR , il manque le preview dans le onChange

J'ai push ma modif avec le preview dans le onChange :)

**Review by arnaudforaison — APPROVED** [review]

**Review by johnmeunier — APPROVED** [review]

**Pull request merged**
