### PR TITLE
fix(table-pager): add flexible width when active page number is large

### PR DESCRIPTION
**Pull request by gcruchon**
### Reference to the issue

#689 

### Description of the issue

When the table had 4-digit number of pages, the active page was truncated and blue bullet not centered

### Person(s) for reviewing proposed changes

@samuel-gomez @guillaumechervet @youf-olivier @LeGrandKhan

### CODE REVIEW

**Review by arnaudforaison — DISMISSED** [review]
LGTM

**Comment by gcruchon** [comment]
Hmmmm I rebased after @samuel-gomez merged PR and lost your approval, @arnaudforaison. Sorry.

**Review by arnaudforaison — APPROVED** [review]

**Comment by youf-olivier** [comment]
Le rebase était vraiment obligatoire ?

**Comment by gcruchon** [comment]
That's my religion, @youf-olivier, I **always** rebase before submitting a PR.

To me: 
- it keeps the history much much much cleaner and understable (history being "passive documentation")
- much safer (even more after a 450+ file PR just merged before mine)

**Comment by youf-olivier** [comment]
De mémoire ca change rien, le merge se débrouille tout seul, mais t'as surement raison.

**Review by youf-olivier — APPROVED** [review]

**Comment by gcruchon** [comment]
Rebase will make sure commits are one after another... while merges may look like this :-)
merge-toolkit

**Comment by gcruchon** [comment]
Anyway, it's your move to merge it now, I don't have the write-access on this repo :)

**Pull request merged**
