### PR TITLE
fix: remove duplicated files

### PR DESCRIPTION
**Pull request by xballoy**
### Description of the issue

When doing a `git checkout` of the project we have the following warning

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'storybook/design-system/src/components/colors/Color.pug'
  'storybook/design-system/src/components/colors/color.pug'
  'storybook/design-system/src/components/colors/Colors.pug'
  'storybook/design-system/src/components/colors/colors.pug'
```

### Person(s) for reviewing proposed changes

@samuel-gomez-axa 

# Important

Before creating a pull request run unit tests

```sh
$ npm test

# watch for changes
$ npm test -- --watch

# For a specific file (e.g., in packages/context/__tests__/command.test.js)
$ npm test -- --watch packages/action
```

### CODE REVIEW

**Comment by samuel-gomez-axa** [comment]
thank you Xavier, it's probably not passed on my last PR

**Comment by xballoy** [comment]
How long does "SonarCloud Code Analysis Expected — Waiting for status to be reported " take?

**Comment by samuel-gomez-axa** [comment]
It's too long, there is a trouble on analysis, @guillaumechervetaxa  can you share us the Sonar Link page analysis, please ?

**Comment by xballoy** [comment]
There is no analysis for this PR: https://sonarcloud.io/dashboard?id=AxaGuilDEv_react-toolkit :(

**Pull request merged**
