### PR TITLE
build: bump react-select to version 3.1.0

### PR DESCRIPTION
**Pull request by xballoy**
Bump react-select to latest version.

I followed the [migration guide](https://github.com/JedWatson/react-select/issues/3585).
The only change for us is the new import for the async react-select component.

@guillaume-chervet @samuel-gomez @youf-olivier

### CODE REVIEW

**Comment by youf-olivier** [comment]
No breaking change on the R3 of react-select ?

**Comment by xballoy** [comment]
The breaking changes are:
- Upgrade from Emotion 9 to Emotion 10 → we don't use it
- UMD builds deprecated → we don't use it
- React 16.8 required as peer dependencies → done with #620 
- Normalized Values [#3416](https://github.com/JedWatson/react-select/pull/3416) → on removal of all selected values in an isMulti Select, the value passed to onChange is null and not []

The last point is the only one that could be a breaking change for us.

**Comment by youf-olivier** [comment]
Can you add a Breaking change info in the commit message ? 

https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.gbbngquhe0qa

**Comment by xballoy** [comment]
I added a breaking change

**Pull request merged**
